gestor_imagenes/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('registro.urls', namespace='registro')),
]

registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views
from registro.views import *
from django.conf import settings
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    #url(r'^$', Index.as_view(), name='index'),
    url(r'^$', LoginView.as_view(), name = "login"),
    url(r'^buscar$', login_required(buscar), name='buscar'),
    url(r'^lista_imagenes$', login_required(views.Lista_imagenes.as_view()), name='lista_imagenes'),
    url(r'^guardar_imagen$', login_required(views.Guardar_imagen.as_view()), name='guardar_imagen'),
    url(r'^editar_imagen/(?P<pk>\d+)$', login_required(views.Editar_imagen.as_view()), name='editar_imagen'),
    url(r'^borrar_imagen/(?P<pk>\d+)$', login_required(views.Borrar_imagen.as_view()), name='borrar_imagen'),
    # Definiendo la url que va a servir las imagenes para que puedan ser descargadas.
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    # Definiendo la url que va a servir las imagenes para que puedan ser descargadas luego de filtrar.
    url(r'^busqueda/media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^busqueda/$', login_required(busqueda), name='busqueda'),
    url(r'^salir$', login_required(views.Salir.as_view()), name='salir'),
)

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse


class Imagen(models.Model):
    """
    Modelo de la imagen digital que se sube al servidor.
    """
    titulo = models.CharField(max_length=255, blank=False, null=False)
    autor = models.CharField(max_length=255, blank=False, null=False)
    imagen = models.FileField(upload_to='', blank=False, null=False)
    tag = models.CharField(max_length=255, blank=False, null=False)
    uploaded_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('registro:editar_imagen', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.titulo

registro/forms.py
# -*- coding: utf-8 -*-
from django import forms
from registro.models import Imagen
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.forms import (
    ModelForm, TextInput, EmailInput, CharField, EmailField, PasswordInput, Select
)
from django import forms


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 25%; display: inline;',
    }), required = True)

    password = forms.CharField(widget=PasswordInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 25%; display: inline;',
    }), required = True)

    class Meta:
        model = User

    fields = [
        'username',
        'password',
    ]


class ImagenForm(forms.ModelForm):
    """
    Formulario del certificado digital que se sube al servidor.
    """
    class Meta:
        model = Imagen
        fields = ('titulo','autor','imagen','tag')

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView,ListView, View
from django.views.generic import FormView, RedirectView, CreateView, DeleteView, UpdateView, ListView, TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from registro.models import Imagen
from registro.forms import ImagenForm
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import forms, login, logout, authenticate
from django.views.generic import View
from django.shortcuts import render_to_response
from django.template import RequestContext
from .forms import LoginForm


class LoginView(FormView):
    template_name = 'registro/login.html'
    form_class = LoginForm

    def get_success_url(self):
        return reverse_lazy('registro:buscar')

    def form_valid(self, form):
        usuario = form.cleaned_data['username']
        contrasena = form.cleaned_data['password']
        usuario = authenticate(username=usuario, password=contrasena)
        login(self.request, usuario)
        return super(LoginView, self).form_valid(form)


class Guardar_imagen(SuccessMessageMixin, CreateView):
    """
    Clase que permite guardar las imagenes, se guardan en /media en
    la raíz del proyecto.
    """
    model = Imagen
    form_class = ImagenForm
    template_name = "registro/guardar_imagen.html"
    success_url = reverse_lazy('registro:buscar')
    success_message = "Se guardó la imagen con éxito"


class Lista_imagenes(ListView):
    """
    Clase que permite listar las imagenes registradas.
    """
    model = Imagen
    template_name = "registro/lista_imagenes.html"


class Editar_imagen(SuccessMessageMixin, UpdateView):
    """
    Clase que permite editar las imagenes registradas.
    """
    template_name = "registro/guardar_imagen.html"
    form_class = ImagenForm
    model = Imagen
    success_message = "Se actualizó la información con éxito"
    success_url = reverse_lazy('registro:buscar')


class Borrar_imagen(SuccessMessageMixin, DeleteView):
    """
    Clase que permite borrar las imagenes.
    """
    form_class = ImagenForm
    model = Imagen
    success_message = "Se eliminó la información con éxito"
    success_url = reverse_lazy('registro:lista_imagenes')


def buscar(request):
    """
    Función que muestra la plantilla con el formulario de búsqueda.
    """
    return render(request, 'registro/buscar.html')


def busqueda(request):
    """
    Función que permite hacer el query con las imagenes ya filtrados.
    """
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        #imagenes = imagen.objects.filter(cedula__icontains=q)
        imagenes = Imagen.objects.filter(tag__icontains=q)
        if imagenes:
            return render(request, 'registro/buscar.html',  {'imagenes': imagenes, 'query': q})
        else:
            messages = ['No se encontró ningúna imagen.']
            return render_to_response('registro/buscar.html', {'messages': messages}, context_instance=RequestContext(request))
    else:
        messages = ['Por favor introduce una etiqueta.']
        return render_to_response('registro/buscar.html', {'messages': messages}, context_instance=RequestContext(request))


class Salir(View):
    """
    Clase que permite cerrar la sesión de usuario.
    """

    def get(self, request):
        """
        Método que redireccíona cuando se cierra la sesión.
        """
        logout(request)
        return redirect('/')

registro/templates/registro/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}
    <link rel="icon" href="{% static 'img/cenditel-logo.png' %}">
    <title>
      {% block titulo %}Gestor de imágenes{% endblock %}
    </title>
    {% load staticfiles %}
    <!-- Bootstrap Styles - css
    ================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Styles - css
    ================================================== -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">
    <!-- Others - js
    ================================================== -->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- Jquery - js
    ================================================== -->
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <!-- Bootstrap - js
    ================================================== -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bug fix - js
    ================================================== -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </head>
  <body>

    <!-- navbar cintillo
    ================================================== -->
    <nav class="navbar navbar-default navbar-fixed-top navbar-cintillo">
    <div class="container">
      <div align="center">
        <img class="cintillo_up" src="{% static 'img/cintillo_2018.png' %}" width="100%"></img>
      </div>
    </div>
    </nav>
    <!-- navbar cintillo end -->

    <br />
    <br />
    <br />
    <br />
 
    <div class="container theme-showcase" role="main">

      <img class="img-responsive" src="{% static 'img/cintillo_cenditel.png' %}" width="100%"></img>

      <br />

      <div class="well">

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-success alert-dismissable">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>
                  {% if message.tags %}{% endif %}
                  {{ message }}
                </strong>
            </div>
          {% endfor %}
        {% endif %}

        <div class="">

          <!-- Navbar
          ================================================== -->
          <nav class="navbar navbar-default navbar-default-menu">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'registro:buscar' %}">
                  <i class="glyphicon glyphicon-home"></i>
                  Inicio
                </a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav">
                  <li>
                    <a href="{% url 'registro:guardar_imagen' %}">
                      <i class="glyphicon glyphicon-upload"></i>
                      Subir imagen
                    </a>
                  </li>
                </ul>
                <!--ul class="nav navbar-nav">
                  <li>
                    <a href="{% url 'registro:lista_imagenes' %}">
                      <i class="glyphicon glyphicon-list"></i>
                      Lista de imagenes
                    </a>
                  </li>
                </ul-->
                <ul class="nav navbar-nav">
                  <li>
                    <a href="{% url 'registro:salir' %}">
                      <i class="glyphicon glyphicon-log-out"></i>
                      Cerrar sesión
                    </a>
                  </li>
                </ul>
                {% else %}
                {% endif %}
              </div>
            </div>
          </nav><!-- End navbar -->
          <br />
          {% block cuerpo %}
          {% endblock %}

        </div>

        <br />
        <br />

      </div>

      <div class="well well-footer">
        <div align="center">
          <b>
            <a href="http://www.cenditel.gob.ve" target="_blank">
              Desarrollado en el Centro Nacional de Desarrollo e Investigacion en Tecnologias Libres - CENDITEL
            </a>
            <br />
            <br />
            <a href="http://conocimientolibre.cenditel.gob.ve/licencias/" target="_blank">
              <img src="{% static 'img/lc-lc.png' %}" width="100px"></img>
            </a>
            <a href="http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/" target="_blank">
              <img src="{% static 'img/lc-ls-icon.png' %}" width="100px"></img>
            </a>
          </b>
        </div>
      </div>

    </div> <!-- /container -->

  </body>

  <script src="{% static 'js/scripts.js' %}"></script>
</html>

registro/templates/registro/buscar.html
{% extends "registro/base.html" %}
{% block titulo %}Gestor de imágenes{% endblock %}
{% block cuerpo %}
<script type="text/javascript">
  document.oncontextmenu = function(){return false;}
</script>
<div align="center">
  <form action="{% url 'registro:busqueda' %}" method="get">
    <h4>
      Escriba la etiqueta y efectúe la búsqueda de imágenes.
    </h4>
    <br />
    <input type="text" name="q" placeholder="" required>
    <br />
    <br />
    <input type="submit" class="btn btn-success" value="Buscar">
  </form>
  <br />
  {% if imagenes %}
  <p>Estas buscado imágenes que coincidan con la etiqueta: <strong>{{ query }}</strong></p>
    <span class="imagenes_encontradas"><b>imagenes encontradas: {{ imagenes|length }}.</b></span>
    <br />
    <br />
    <table class="table table-striped" border="1px">
      <thead>
        <tr>
          <th><b>Título</b></th>
          <th><b>Autor</b></th>
          <th><b>Etiquetas</b></th>
          <th><b>Imagen</b></th>
          <th><b>Ubicación electróica</b></th>
        </tr>
      </thead>
      {% for x in imagenes %}
      <tbody>
        <tr>
          <td>
            {{ x.titulo }}
          </td>
          <td>
            {{ x.autor }}
          </td>
          <td>
            {{ x.tag }}
          </td>
          <td>
            <img src="media/{{ x.imagen }}" class="img-thumbnail" width="400px">
          </td>
          <td>
            <a href="media/{{ x.imagen }}" class="link_descarga" target="_blank" download>
              Descargar
              <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
            </a>
          </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
    <br />
    <br />
  {% else %}
    <!--p>Ninguna imagen coincide con el criterio de búsqueda.</p-->
  {% endif %}
</div>
{% endblock %}

registro/templates/registro/guardar_imagen.html
{% extends "registro/base.html" %}
{% block titulo %}Subir imágen{% endblock %}
{% block cuerpo %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}

  <label>{{ form.titulo.label }}:</label>
  {{ form.titulo }}
  {% if form.titulo.errors %}
    <p>{{ form.titulo.errors}}</p>
  {% endif %}

  <hr />

  <label>{{ form.imagen.label }}:</label>
  {{ form.imagen }}
  {% if form.imagen.errors %}
    <p>{{ form.imagen.errors}}</p>
  {% endif %}

  <hr />

  <label>{{ form.autor.label }}:</label>
  {{ form.autor }}
  {% if form.autor.errors %}
    <p>{{ form.autor.errors}}</p>
  {% endif %}

  <hr />

  <label>Etiqueta/s:</label>
  {{ form.tag }}
  <p>Las etiquetas deben ir separadas por espacios</p>
  {% if form.tag.errors %}
    <p>{{ form.tag.errors}}</p>
  {% endif %}

  <hr />

  <button class="btn btn-primary" type="reset">Limpiar campos</button>
  <button class="btn btn-success" type="submit">Subir imágen</button>
</form>
{% endblock %}

registro/templates/registro/imagen_confirm_delete.html
{% extends "registro/base.html" %}
{% block titulo %}Gestor de imágenes{% endblock %}
{% block cuerpo %}
<form method="post">{% csrf_token %}
  Está seguro que desea eliminar la imagen: "{{ object }}" ?
  <br />
  <br />
  <input type="submit" class="btn btn-danger" value="Borrar" />
</form>
{% endblock %}

registro/templates/registro/index.html
{% extends "registro/base.html" %}
{% block titulo %}Gestor de imágenes{% endblock %}
{% block cuerpo %}
<div align="center">
  <h1>Gestor de imágenes</h1>
</div>
{% endblock %}

registro/templates/registro/lista_imagenes.html
{% extends "registro/base.html" %}
{% block titulo %}Lista de imágenes{% endblock %}
{% block cuerpo %}
<h1>Lista de imágenes</h1>
<br />
<table class="table table-striped" border="1px">
  <thead>
    <tr>
      <th><b>ID</b></th>
      <th><b>Título</b></th>
      <th><b>Autor</b></th>
      <th><b>Etiquetas</b></th>
      <th><b>Imagen</b></th>
      <th><b>Ubicación electrónica</b></th>
      <th><b>Acciones</b></th>
    </tr>
  </thead>
  {% for x in object_list %}
  <tbody>
    <tr>
      <td>
        {{ x.id }}
      </td>
      <td>
        {{ x.autor }}
      </td>
      <td>
        {{ x.titulo }}
      </td>
      <td>
        {{ x.tag }}
      </td>
      <td>
        <img src="media/{{ x.imagen }}" class="img-thumbnail" width="400px">
      </td>
      <td>
        <a href="media/{{ x.imagen }}" target="_blank">
          Descargar
          <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
        </a>
      </td>
      <td>
        <a href="{% url 'registro:editar_imagen' x.id %}">
          <button class="btn btn-primary">Editar</button>
        </a>
        <a href="{% url 'registro:borrar_imagen' x.id %}">
          <button class="btn btn-danger">Borrar</button>
        </a>  
      </td>
    </tr>
  </tbody>
  {% endfor %}
</table>
{% endblock %}

registro/templates/registro/login.html
{% extends "registro/base.html" %}
{% block titulo %}Gestor de imágenes{% endblock %}
{% block cuerpo %}
<div align="center">
  <h1>Gestor de imágenes</h1>
  <br />
  <h3>Iniciar sesión</h3>
  <form action="{% url 'registro:login' %}" method="post">{% csrf_token %}
    <br />
    <b>Usuario</b><br />
    {{ form.username }}
    <br />
    <br />
    <b>Contraseña</b>
    <br />
    {{ form.password }}
    <br />
    <br />
    <button class="btn btn-success" type="submit">Iniciar sesión</button>
  </form>
</div>
{% endblock %}